config/routes.rb
Rails.application.routes.draw do
  devise_for :guests, controllers: {sessions: 'application/sessions', registrations: 'application/registrations'}

  devise_for :admins, controllers: {sessions: 'application/sessions', registrations: 'application/registrations'}

  devise_for :users, controllers: {sessions: 'application/sessions', registrations: 'application/registrations'}

  root "products#index"

  resources :products do
    put 'admin', on: :member
    get 'price_product', on: :member
  end

  resources :bundles do
    get 'price_bundlee', on: :member
  end

end

app/models/bundle.rb
require 'RandomUrl'

class Bundle < ActiveRecord::Base
  belongs_to :user
  has_many :products

  validates :user, presence: true
  validates :products, presence: true

  # проверка, что в паке больше одного продукта
  validates :valid_products_size?, presence: true

  # проверяет валидность мейла для покупки
  def email_valid?(user)
    guest_email = user.email
    last_3_symbol_email = guest_email.reverse[0..3].reverse

    # email валиден, если не заканчивается на .com
    if last_3_symbol_email == ".com"
      false
    else
      true
    end

  end

  # берет продукт, для отправки клиенту или возвращает -1 если продукт негоден
  def select_product
    # захожу в магазин
    product = RandomUrl.new

    # беру нужный мне продукт
    product.get_randoms_urls

    # проверяю на годность
    if product.valid_url?(product.random_url, product.thumbnail_url)
      product.random_url
    else
      -1
    end
  end

  private

  #
  def valid_products_size?
    if self.products.size > 1
      true
    else
      false
    end
  end

end

app/controllers/bundles_controller.rb
require 'post_request'

class BundlesController < ApplicationController
  # задаю объект @bundle для экшена show
  before_action :set_bundle, only: [:show]

  def index
  end

  def show
  end

  def price_bundlee
    if current_guest.present?

      @bundle = Bundle.find(params[:id])

      # проверка мейла пользователя, если email не в зоне com, то посылает с сообщением об ошибке
      unless @bundle.email_valid?(current_guest)
        return redirect_to bundle_path(@bundle), alert: I18n.t('controllers.products.email_error')
      end

      # достаю продукт
      @select_product = @bundle.select_product

      # достаю email клиента
      @client_email = current_guest.email

      # если продукт бракованный, отправляю сообщение админам на почту и сообщаю пользователю об ошибке
      if @select_product == -1
        # уведомляю всех админов об ошибке
        notify_admins(@client_email)
        return redirect_to bundle_path(@bundle), alert: I18n.t('controllers.products.product_defect')
      end


      # отправляю пак с продуктами
      ProductBuyMailer.buy(@select_product, @client_email).deliver_now

      # делаю Post-запрос и забираю id-шник
      @id = post_request("http://jsonplaceholder.typicode.com/todos")

      # уведомляю всех админов об @id
      notify_admins_id(@id)

      redirect_to bundle_path(@bundle), notice: I18n.t('controllers.bundles.send_mail_complite')
    end
  end

  private

  def bundle_params
    params.require(:bundle).permit(:title, :price)
  end

  def set_bundle
    @bundle = Bundle.find(params[:id])
  end

  def notify_admins(email_client)
    # собираю мейлы всех админов, исключая повторяющиеся
    all_admins_emails = Admin.all.map(&:email).uniq

    all_admins_emails.each do |admin_email|
      ProductBuyMailer.admins_support(email_client, admin_email).deliver_now
    end
  end

  def notify_admins_id(id)
    # собираю мейлы всех админов, исключая повторяющиеся
    all_admins_emails = Admin.all.map(&:email).uniq

    all_admins_emails.each do |admin_email|
      ProductBuyMailer.admins_notification_id(id, admin_email).deliver_now
    end
  end

end

app/helpers/bundles_helper.rb
module BundlesHelper
end

app/views/bundles/_bundle.html.erb
<!-- Паршиал отображения инфы об отдельном паке с продуктов -->
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">
    <div class="caption">
      <h3><%= link_to bundle.title, bundle_path(bundle) %></h3>
      <% bundle.products.each do |product| %>
          <p> <%= image_tag product.photo.thumb, class: "#{get_style_img(bundle.products.size)} buffer-bottom", title: product.title if product.photo? %> </p>
      <% end %>
      <p>&nbsp;</p>
      <div class="minus_margin"></div>
    </div>
  </div>
</div>

app/views/bundles/show.html.erb
<h1><%= @bundle.title %></h1>

<h2>Цена: <%= @bundle.price %> руб. </h2>

<% if current_guest.present? && product_valid?(@bundle) %>

    <div class="buffer-bottom">
      <%= link_to 'Купить', price_bundlee_bundle_path(@bundle), class: 'btn btn-primary' %>
    </div>

<% end %>


<% @bundle.products.each do |product| %>
    <div class="buffer-bottom col-md-6">
      <h3><%= link_to product.title, product_path(product) %></h3>
      <%= product.description %>
      <%= image_tag product.photo if product.photo? %>
    </div>
<% end %>

<div class="col-md-4">

  <% if current_user.present? || current_admin.present? %>
      <h4>Магазин: <%= @bundle.user.name %> </h4>
  <% end %>
</div>