config/routes.rb
Rails.application.routes.draw do
  devise_for :guests, controllers: {sessions: 'application/sessions', registrations: 'application/registrations'}

  devise_for :admins, controllers: {sessions: 'application/sessions', registrations: 'application/registrations'}

  devise_for :users, controllers: {sessions: 'application/sessions', registrations: 'application/registrations'}

  root "products#index"

  resources :products do
    put 'admin', on: :member
    get 'price_product', on: :member
  end

  resources :bundles do
    get 'price_bundlee', on: :member
  end

end

app/models/product.rb
require 'RandomUrl'

class Product < ActiveRecord::Base
  belongs_to :user
  belongs_to :bundle

  validates :user, presence: true
  validates :title, presence: true, length: {maximum: 35}

  mount_uploader :photo, PhotoUploader

  # обновляет статус продукта
  def update_status!
    toggle!(:pro)
  end


  # проверяет валидность мейла для покупки
  def email_valid?(user)
    guest_email = user.email
    last_3_symbol_email = guest_email.reverse[0..3].reverse

    # email валиден, если не заканчивается на .com
    if last_3_symbol_email == ".com"
      false
    else
      true
    end

  end

  # берет продукт, для отправки клиенту или возвращает -1 если продукт негоден
  def select_product
    # захожу в магазин
    product = RandomUrl.new

    # беру нужный мне продукт
    product.get_randoms_urls

    # проверяю на годность
    if product.valid_url?(product.random_url, product.thumbnail_url)
      product.random_url
    else
      -1
    end
  end

end

app/controllers/products_controller.rb
require 'post_request'

class ProductsController < ApplicationController

  # задаю объект @product для экшена show
  before_action :set_product, only: [:show]

  # задаю объект @product от текущего юзера
  before_action :set_current_user_product, only: [:edit, :update, :destroy]

  def index
    @products = Product.all
    @bundles = Bundle.all
  end

  def new
    @product = current_user.products.build
  end

  def create
    @product = current_user.products.build(product_params)

    if @product.save
      redirect_to @product, notice: I18n.t('controllers.products.created')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: I18n.t('controllers.products.update')
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, notice: I18n.t('controllers.products.destroyed')
  end

  # отвечает за то, что админ может обновлять статус продукта
  def admin
    if current_admin.present?
      @product = Product.find(params[:id]) # нахожу текущий продукт
      @product.update_status!
      redirect_to product_path, notice: I18n.t('controllers.products.status_update')
    end
  end

  # Экшен, который обрабатывает покупки пользователей (Guest)
  def price_product
    @product = Product.find(params[:id]) # нахожу текущий продукт
    if current_guest.present? && !@product.user.name.nil? && @product.pro == false

      # проверка мейла пользователя, если email не в зоне com, то посылает с сообщением об ошибке
      unless @product.email_valid?(current_guest)
        return redirect_to product_path(@product), alert: I18n.t('controllers.products.email_error')
      end

      # достаю продукт
      @select_product = @product.select_product

      # достаю email клиента
      @client_email = current_guest.email

      # если продукт бракованный, отправляю сообщение админам на почту и сообщаю пользователю об ошибке
      if @select_product == -1
        # уведомляю всех админов об ошибке
        notify_admins(@client_email)
        return redirect_to product_path(@product), alert: I18n.t('controllers.products.product_defect')
      end


      # отправляю продукт
      ProductBuyMailer.buy(@select_product, @client_email).deliver_now

      # делаю Post-запрос и забираю id-шник
      @id = post_request("http://jsonplaceholder.typicode.com/todos")

      # уведомляю всех админов об @id
      notify_admins_id(@id)

      redirect_to product_path(@product), notice: I18n.t('controllers.products.send_mail_complite')
    end
  end

  private

  def set_current_user_product
    @product = current_user.products.find(params[:id])
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :photo)
  end

  def notify_admins(email_client)
    # собираю мейлы всех админов, исключая повторяющиеся
    all_admins_emails = Admin.all.map(&:email).uniq

    all_admins_emails.each do |admin_email|
      ProductBuyMailer.admins_support(email_client, admin_email).deliver_now
    end
  end

  def notify_admins_id(id)
    # собираю мейлы всех админов, исключая повторяющиеся
    all_admins_emails = Admin.all.map(&:email).uniq

    all_admins_emails.each do |admin_email|
      ProductBuyMailer.admins_notification_id(id, admin_email).deliver_now
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :photo %>
      <p><%= image_tag(@product.photo.thumb.url) if @product.photo? %></p>
      <%= f.file_field :photo %>
    </div>

    <div class="actions">
      <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
      <% if @product.persisted? %>
          <%= link_to 'Удалить продукт', product_path(@product), method: :delete, data: {confirm: 'Действительно ли вы хотите удалить продукт?'}, class: 'btn btn-primary' %>
      <% end %>
      или <%= link_to 'вернуться', :back %>
    </div>
<% end %>

app/views/products/_product.html.erb
<!-- Паршиал отображения инфы об отдельном продукте -->
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">

    <div class="caption">
      <h3><%= link_to product.title, product_path(product) %></h3>
      <p> <%= image_tag product.photo.thumb if  product.photo? %> </p>

      <% if product.pro && (current_user.present? || current_admin.present? || current_guest.present?) %>
          <p>PRO</p>
      <% end %>

    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Редактирование продукта</h1>

<div class="row">
  <div class="col-md-6 buffer-top">

    <%= render 'form' %>
  </div>
</div>

app/views/products/index.html.erb
<h1>Продукты</h1>

<% if user_signed_in? %>
    <div class="buffer-bottom">
      <%= link_to 'Создать продукт', new_product_path, class: 'btn btn-success' %>
    </div>
<% end %>

<div class="row buffer-bottom">
  <!-- Рендерим сразу массив событий, каждый в паршиале 'products/product' -->
  <%= render partial: 'products/product', collection: @products %>
  <%= render partial: 'bundles/bundle', collection: @bundles %>
</div>

app/views/products/new.html.erb
<h1>Новый продукт</h1>

<div class="row">
  <div class="col-md-6 buffer-top">

    <%= render 'form' %>
  </div>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><%= @product.title %></h1>
    <% if @product.pro && (current_user.present? || current_admin.present? || current_guest.present?) %>
        <h1>PRO</h1>
    <% end %>

    <% if current_admin.present? %>
        <div class="buffer-bottom">
          <%= link_to 'Сменить статус', admin_product_path(@product), method: :put, class: 'btn btn-primary' %>
        </div>
    <% end %>

      <% if current_guest.present? && product_valid?(@product) && @product.pro == false %>

        <div class="buffer-bottom">
          <%= link_to 'Купить', price_product_product_path(@product), class: 'btn btn-primary' %>
        </div>

    <% end %>

    <p><%= @product.description %></p>
  </div>
</div>


<p> <%= image_tag @product.photo if @product.photo? %> </p>

<div class="col-md-4">

  <% if current_user.present? || current_admin.present? %>
      <h4>Магазин: <%= @product.user.name %> </h4>
  <% end %>

  <% if current_user_can_edit?(@product) %>
      <div class="buffer-top">
        <%= link_to 'Изменить', edit_product_path(@product), class: 'btn btn-primary' %>
      </div>
  <% end %>
</div>