config/routes.rb
Rails.application.routes.draw do
  devise_for :guests, controllers: {sessions: 'application/sessions', registrations: 'application/registrations'}

  devise_for :admins, controllers: {sessions: 'application/sessions', registrations: 'application/registrations'}

  devise_for :users, controllers: {sessions: 'application/sessions', registrations: 'application/registrations'}

  root "products#index"

  resources :products do
    put 'admin', on: :member
    get 'price_product', on: :member
  end

  resources :bundles do
    get 'price_bundlee', on: :member
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Продукты" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>

<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'Продукты', root_path, class: 'navbar-brand' %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
            <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
        <% elsif admin_signed_in? %>
            <li><%= link_to 'Выйти', destroy_admin_session_path, :method => :delete %></li>
        <% elsif guest_signed_in? %>
            <li><%= link_to 'Выйти', destroy_guest_session_path, :method => :delete %></li>
        <% else %>
            <li><%= link_to 'Войти', new_guest_session_path %></li>
            <li><%= link_to 'Зарегистрироваться', new_guest_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-9">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div><!--/row-->

  <footer>
    <p>&copy; <%= t 'app.company' %> 2016</p>
  </footer>

</div> <!-- /container -->

</body>
</html>